default: &default
  adapter: postgresql
  encoding: unicode
  
development:
  <<: *default
  database: daily_development
  user: stokwell
  host: localhost

test:
  <<: *default
  database: daily_test

production:
  <<: *default
  database: daily_production
  username: stokwell
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
