default: &default
  adapter: postgresql
  user: vlyapunov
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: daily_development

test:
  <<: *default
  database: daily_test

production:
  <<: *default
  database: daily_production
