
default: &default
  adapter: postgresql
  user: stokwell

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
