# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a50ed1f534ee64f522aa51676f8772a0f3224f5083da0767ca769c35e794ee20aa3008da84e5a6e6ea968b83fab211725cb97bb2a163b7b7a8355127078ddc8b

test:
  secret_key_base: 62f3d04eafb035bd9ca4a9f1548d17cadd9868af557701ac492eb1943f08fa43ae9abcc8aeff54ecb87db5ac06fe2a348dfed6cf4f456447f1b8ab3d704f71d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
